name: BSL Code Analysis

on:
  pull_request:
    branches:
      - main

jobs:
  bsl-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show repository structure
        run: |
          pwd
          ls -la
          ls -la UT_Marketplaces.Marketplaces || true
          ls -la UT_Marketplaces.Marketplaces/src || true

      - name: Show BSL analyze help
        run: |
          docker run --rm \
            1csyntax/bsl-language-server:latest \
            analyze --help || true