name: Test EDT

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    env:
      EDT_CLI: ${{ vars.EDT_PATH }}
    steps:
      - name: Test EDT version
        shell: cmd
        run: |
          echo User: %USERNAME%
          echo EDT: %EDT_CLI%
          "%EDT_CLI%\1cedtcli.exe" -data "C:\EDT_Workspace_CI" -command version
